version: "3.8"
services:
    client:
        build:
            context: ./client
        ports:
            - "6681:6681"
        container_name: client
        depends_on:
            - nginx

    server:
        build:
            context: ./server
        ports:
            - "6682:6682"
        container_name: server
        depends_on:
            - nginx

    nginx:
        restart: always
        image: nginx:latest
        container_name: nginx
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"